# Generated by Django 4.2.9 on 2025-08-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_options_alter_size_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='abbreviation',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
